### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by adamgajzlerowicz** [saschwarz/agility-jump-heights#1]
Hi Steve :)

I also enjoy dog agility a lot. I came across your youtube channel. I really like both - the name and the materials :smile: 

I love all the learning stuff you made! Thank you so much for that. As a beginner agility practitioner (2 years) I find them super helpful.

Just wanted to get in touch really. If you need any help with programming, or you were going to start working on a new agility app of some sort - I'd love to help!

**Comment by saschwarz** [comment]
Hi Adam,

I'm glad you enjoy my dog agility work! If you haven't seen my other dog agility/web "stuff" here are some links that might be interesting:

https://agilitycoursemaster.com
Blogs: https://agilitynerd.com/  https://tech.agilitynerd.com/
Dog Agility Search: https://googility.com/
Dog Agility Courses: https://agilitycourses.com/
https://www.facebook.com/AgilityNerd

I've mostly worked alone, but I'll definitely keep you in mind for the future!
Run Clean, Run Fast, Run Fun!
